run:
  timeout: 5m
  modules-download-mode: readonly
  skip-dirs:
    - vendor
    - docs
    - scripts

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - typecheck
    - gofmt
    - goimports
    - misspell
    - unconvert
    - unparam
    - gocritic
    - gosec
    - bodyclose
    - noctx
    - errorlint

linters-settings:
  govet:
    check-shadowing: false
  gofmt:
    simplify: true
  goimports:
    local-prefixes: github.com/NAEOS-foundation/naeos
  misspell:
    locale: US
  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance
  gosec:
    excludes:
      - G104  # unhandled errors on deferred close
  errorlint:
    errorf: true
    asserts: true
    comparison: true

issues:
  exclude-generated: true
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
        - errcheck
    - path: "zz_generated.*"
      linters:
        - govet
        - errcheck
        - staticcheck
        - unused
        - gosimple
        - ineffassign
        - typecheck
  max-issues-per-linter: 0
  max-same-issues: 0
