run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - misspell
    - unconvert
    - gocritic
    - gosec

linters-settings:
  govet:
    check-shadowing: false
  gofmt:
    simplify: true
  goimports:
    local-prefixes: github.com/NAEOS-foundation/naeos
  misspell:
    locale: US
  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
        - errcheck
  max-issues-per-linter: 0
  max-same-issues: 0
