package main

import (
	"fmt"
	"os"
	"strings"

	"github.com/spf13/cobra"

	"github.com/NAEOS-foundation/naeos/internal/generation/adapters"
	"github.com/NAEOS-foundation/naeos/internal/neir/model/language"
)

func newScaffoldCommand() *cobra.Command {
	var name, output string
	var languages []string

	cmd := &cobra.Command{
		Use:   "scaffold",
		Short: "Generate a starter project scaffold",
		Long: `Generate a starter project scaffold with all necessary files.

Example:
  naeos scaffold --name my-app
  naeos scaffold --name my-app --output ./my-app --language typescript
  naeos scaffold --name my-app --language go --language python`,
		Args: cobra.NoArgs,
		RunE: func(cmd *cobra.Command, args []string) error {
			if name == "" {
				return fmt.Errorf("missing required --name")
			}
			if output == "" {
				output = name
			}

			if err := os.MkdirAll(output, 0o755); err != nil {
				return fmt.Errorf("create scaffold dir: %w", err)
			}

			targetLangs := resolveScaffoldLanguages(languages)

			for _, lang := range targetLangs {
				adapter, ok := adapters.Get(lang)
				if !ok {
					continue
				}
				artifacts := adapter.GenerateProject(name)
				artifacts = append(artifacts, adapter.GenerateDockerfile(name)...)
				artifacts = append(artifacts, adapter.GenerateCI(name)...)

				for _, a := range artifacts {
					if err := writeFileInDir(output, a.Path, string(a.Content)); err != nil {
						return err
					}
				}

				coreArtifacts := adapter.GenerateModule("core", "./internal/core", name)
				for _, a := range coreArtifacts {
					if err := writeFileInDir(output, a.Path, string(a.Content)); err != nil {
						return err
					}
				}

				extraModuleFiles := map[string]string{
					"internal/core/README.md":     "# core\n\nCore module for " + name + ".\n\n## Overview\n\nThis module contains the core business logic.\n",
					"internal/core/package.go":    "package core\n\n// " + name + " core module.\n// Contains domain models and business logic.\n",
					"internal/core/config.yaml":   "name: core\nmodule: core\nversion: 0.1.0\ndescription: Core module for " + name + "\n",
					"internal/core/domain.go":     "package core\n\n// Domain models for " + name + ".\n\ntype Entity struct {\n\tID   string\n\tName string\n}\n\nfunc NewEntity(id, name string) *Entity {\n\treturn &Entity{ID: id, Name: name}\n}\n",
					"internal/core/service.go":    "package core\n\n// Service layer for " + name + ".\n\ntype Service struct {\n\trepo Repository\n}\n\nfunc NewService(repo Repository) *Service {\n\treturn &Service{repo: repo}\n}\n\nfunc (s *Service) Process(entity *Entity) error {\n\treturn s.repo.Save(entity)\n}\n",
					"internal/core/repository.go": "package core\n\n// Repository interface for " + name + ".\n\ntype Repository interface {\n\tSave(entity *Entity) error\n\tFindByID(id string) (*Entity, error)\n}\n",
				}
				for fileName, content := range extraModuleFiles {
					if err := writeFileInDir(output, fileName, content); err != nil {
						return err
					}
				}
			}

			readme := fmt.Sprintf("# %s\n\nGenerated by NAEOS scaffold.\n\n## Quick start\n\n1. Review spec.yaml\n2. Run 'go mod init %s' (for Go projects)\n3. Run 'go build ./cmd/%s/'\n4. Run './%s'\n\n## Structure\n\n- `internal/core/` - Core business logic\n- `spec.yaml` - Project specification\n- `Makefile` - Build automation\n", name, name, name, name)
			spec := fmt.Sprintf("project: %s\nversion: 0.1.0\ndescription: A new NAEOS project\nmodules:\n  - name: core\n    path: ./internal/core\n    version: 0.1.0\nservices:\n  - name: api\n    kind: http\n    port: 8080\n    module: core\n", name)
			makefile := fmt.Sprintf(".PHONY: help build test run clean\n\nhelp:\n\t@echo 'Available targets:'\n\t@echo '  make help     - Show this help'\n\t@echo '  make build    - Build the project'\n\t@echo '  make test     - Run tests'\n\t@echo '  make run      - Run the application'\n\t@echo '  make clean    - Clean build artifacts'\n\nbuild:\n\t@echo 'Building %s...'\n\t@go build -o bin/%s ./cmd/%s/\n\ntest:\n\t@echo 'Running tests...'\n\t@go test ./...\n\nrun: build\n\t@echo 'Running %s...'\n\t@./bin/%s\n\nclean:\n\t@echo 'Cleaning...'\n\t@rm -rf bin/ out/\n", name, name, name, name, name)
			gitignore := "# Build artifacts\n/bin/\n/out/\n*.log\n*.exe\n*.test\n*.out\n\n# IDE\n.idea/\n.vscode/\n*.swp\n*.swo\n\n# OS\n.DS_Store\nThumbs.db\n"

			baseFiles := map[string]string{
				"README.md":           readme,
				"spec.yaml":           spec,
				"Makefile":            makefile,
				".gitignore":          gitignore,
				"config.yaml":         fmt.Sprintf("port: 8080\nname: %s\nversion: 0.1.0\n", name),
				"config.json":         fmt.Sprintf("{\"port\": 8080, \"name\": \"%s\", \"version\": \"0.1.0\"}\n", name),
				"docker-compose.yaml": fmt.Sprintf("version: '3.8'\nservices:\n  app:\n    build: .\n    ports:\n      - \"8080:8080\"\n    environment:\n      - PORT=8080\n      - NAME=%s\n", name),
				"Dockerfile":          fmt.Sprintf("FROM golang:1.21-alpine AS builder\nWORKDIR /app\nCOPY go.mod go.sum ./\nRUN go mod download\nCOPY . .\nRUN go build -o /app/bin/%s ./cmd/%s/\n\nFROM alpine:latest\nWORKDIR /app\nCOPY --from=builder /app/bin/%s .\nEXPOSE 8080\nCMD [\"./%s\"]\n", name, name, name, name),
			}

			for fileName, content := range baseFiles {
				if err := writeFileInDir(output, fileName, content); err != nil {
					return err
				}
			}

			_, err := fmt.Fprintf(cmd.OutOrStdout(), "scaffolded %s for %s\n", output, strings.Join(targetLangNames(targetLangs), ", "))
			return err
		},
	}

	cmd.Flags().StringVar(&name, "name", "", "project name for the scaffold")
	cmd.Flags().StringVar(&output, "output", "", "directory where scaffold files will be created")
	cmd.Flags().StringArrayVar(&languages, "language", nil, "target language for code generation (go, typescript, python, java, rust)")
	return cmd
}

func resolveScaffoldLanguages(languages []string) []language.Language {
	if len(languages) == 0 {
		return []language.Language{language.LanguageGo}
	}
	var langs []language.Language
	for _, l := range languages {
		langs = append(langs, language.Language(l))
	}
	return langs
}

func targetLangNames(langs []language.Language) []string {
	var names []string
	for _, l := range langs {
		names = append(names, string(l))
	}
	return names
}
