package main

import (
	"fmt"
	"os"

	"github.com/spf13/cobra"

	"github.com/NAEOS-foundation/naeos/internal/workspace"
)

func newWorkspaceCommand() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "workspace",
		Short: "Manage multi-module workspaces",
		Long: `Manage multi-module workspaces for NAEOS projects.

Example:
  naeos workspace init my-workspace
  naeos workspace add my-module ./modules/my-module
  naeos workspace list
  naeos workspace remove my-module`,
	}

	var rootDir string

	wsInit := &cobra.Command{
		Use:   "init [name]",
		Short: "Initialize a workspace",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			mgr := workspace.NewManager(rootDir)
			ws, err := mgr.Init(args[0])
			if err != nil {
				return err
			}
			fmt.Fprintf(cmd.OutOrStdout(), "Initialized workspace %s at %s\n", ws.Name, ws.Root)
			return nil
		},
	}

	wsAdd := &cobra.Command{
		Use:   "add [name] [path]",
		Short: "Add a module to the workspace",
		Args:  cobra.ExactArgs(2),
		RunE: func(cmd *cobra.Command, args []string) error {
			mgr := workspace.NewManager(rootDir)
			if err := mgr.AddModule(args[0], args[1], "", nil); err != nil {
				return err
			}
			fmt.Fprintf(cmd.OutOrStdout(), "Added module %s\n", args[0])
			return nil
		},
	}

	wsRemove := &cobra.Command{
		Use:   "remove [name]",
		Short: "Remove a module from the workspace",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			mgr := workspace.NewManager(rootDir)
			if err := mgr.RemoveModule(args[0]); err != nil {
				return err
			}
			fmt.Fprintf(cmd.OutOrStdout(), "Removed module %s\n", args[0])
			return nil
		},
	}

	wsList := &cobra.Command{
		Use:   "list",
		Short: "List workspace modules",
		RunE: func(cmd *cobra.Command, args []string) error {
			mgr := workspace.NewManager(rootDir)
			modules, err := mgr.ListModules()
			if err != nil {
				return err
			}
			if len(modules) == 0 {
				fmt.Fprintln(cmd.OutOrStdout(), "No modules in workspace")
				return nil
			}
			for _, m := range modules {
				fmt.Fprintf(cmd.OutOrStdout(), "%-20s %s\n", m.Name, m.Path)
			}
			return nil
		},
	}

	cmd.AddCommand(wsInit)
	cmd.AddCommand(wsAdd)
	cmd.AddCommand(wsRemove)
	cmd.AddCommand(wsList)
	cmd.AddCommand(newWorkspaceInfoCommand(&rootDir))
	cmd.AddCommand(newWorkspaceLockCommand(&rootDir))
	cmd.PersistentFlags().StringVar(&rootDir, "root", ".", "workspace root directory")
	return cmd
}

func newWorkspaceInfoCommand(rootDir *string) *cobra.Command {
	return &cobra.Command{
		Use:   "info",
		Short: "Show workspace information and status",
		RunE: func(cmd *cobra.Command, args []string) error {
			mgr := workspace.NewManager(*rootDir)
			modules, err := mgr.ListModules()
			if err != nil {
				return err
			}
			_, _ = cmd.OutOrStdout().Write([]byte("Workspace Information\n"))
			_, _ = cmd.OutOrStdout().Write([]byte("─────────────────────\n"))
			fmt.Fprintf(cmd.OutOrStdout(), "Root:     %s\n", *rootDir)
			fmt.Fprintf(cmd.OutOrStdout(), "Modules:  %d\n", len(modules))
			if len(modules) > 0 {
				_, _ = cmd.OutOrStdout().Write([]byte("\nModules:\n"))
				for _, m := range modules {
					fmt.Fprintf(cmd.OutOrStdout(), "  • %-20s %s\n", m.Name, m.Path)
				}
			}
			return nil
		},
	}
}

func newWorkspaceLockCommand(rootDir *string) *cobra.Command {
	return &cobra.Command{
		Use:   "lock",
		Short: "Generate or update workspace lockfile",
		Long:  `Generate a naeos.lock file that pins all module versions for reproducible builds.`,
		RunE: func(cmd *cobra.Command, args []string) error {
			mgr := workspace.NewManager(*rootDir)
			modules, err := mgr.ListModules()
			if err != nil {
				return err
			}

			var content string
			content += "# NAEOS Workspace Lockfile\n"
			content += "# Generated by: naeos workspace lock\n\n"
			for _, m := range modules {
				content += fmt.Sprintf("%s:\n  path: %s\n  version: latest\n", m.Name, m.Path)
			}

			lockPath := *rootDir + "/naeos.lock"
			if err := os.WriteFile(lockPath, []byte(content), 0o600); err != nil {
				return fmt.Errorf("write lockfile: %w", err)
			}
			fmt.Fprintf(cmd.OutOrStdout(), "Created %s (%d modules locked)\n", lockPath, len(modules))
			return nil
		},
	}
}
